Prepare 2.3.0 release
PelionIoT/manifest-lmp-pelion-edge pull request #20
Opened 2021-04-01 20:59 UTC by x85446

2021-04-01 21:09 UTC, cmonr approved these changes

2021-04-01 21:14 UTC, ygoyal18 approved these changes
LGTM

2021-04-02 00:49 UTC, cmonr requested changes
Blocking until CI is functinal again.

2021-04-04 12:16 UTC, JanneKiiskila commented
Hashes match to latest in main/master in all 3 repos.

2021-04-06 10:34 UTC, merged