local.conf / license info gathering
PelionIoT/manifest-lmp-pelion-edge pull request #68
Opened 2021-10-06 12:28 UTC by JanneKiiskila

Generate the license information as part of build process. License summary gets collected under `/deploy/licences/<image-type-target-timestamp>/license.manifest`.

2021-10-07 05:56 UTC, AriParkkila approved these changes

2021-10-07 08:43 UTC, kivaisan requested changes

2021-10-07 08:46 UTC, kivaisan commented on conf/local.conf
> +LICENSE_CREATE_PACKAGE = "1
```suggestion
LICENSE_CREATE_PACKAGE = "1"
```

2021-11-17 07:51 UTC, JanneKiiskila commented
Not needed.

2021-11-17 07:51 UTC, closed without merging